### ISSUE TITLE
Issues with WebP images

### ISSUE THREAD

**Issue by matejdro** [bunglegrind/save-as-ebook#17]
Attempting to save https://www.phoronix.com/news/Google-Linux-Binder-In-Rust results in a:

`Error: Error! Unable to extract the image type! img-126424042635.TODO-EXTRACT https://www.phoronix.com/assets/categories/google.webp`

Maybe this kind of error could be made non-fatal (e.g. ignore the image, but still extract the rest)?

**Comment by bunglegrind** [comment]
The fix is quite easy (as a personal remainder, webp header is 52 49 46 46), however I've no idea if ebook softwares (kindle, kobo, koreader...) support webp images. 

Yes, I agree...it's not a good idea to have a fatal errore when an image format is unsupported. I've opened a dedicated issue #19
