### ISSUE TITLE
Signed Firefox release

### ISSUE THREAD

**Issue by matejdro** [bunglegrind/save-as-ebook#18]
Hello,

Thanks for maintaining an updated fork of this extension. Any chance you could release a signed version for Firefox?

Thanks to Firefox's stupid restrictions, you can only load unsigned addons temporarily (they will be unloaded on the next browser start).

Thanks.

**Comment by bunglegrind** [comment]
Definitely not a chance. I know it's quite annoying the way Firefox is managing temporary extension, but the only feasible way is to ask @alexadam to merge or whatever this fork to the main branch...

**Comment by matejdro** [comment]
Well, it was worth a try. Thanks for explaining.
