### ISSUE TITLE
Weird data:image svg tag

### ISSUE THREAD

**Issue by matejdro** [bunglegrind/save-as-ebook#20]
[This article](https://maribor24.si/lokalno/maribor/prihodnost-mariborskih-mestnih-avtobusov-digitalna-elektricna-zelena) has following tag that will abort the export:

`<img class="lazy" width="178" height="25" src="data:image/svg+xml,%3Csvg%20xmlns='http://www.w3.org/2000/svg'%20viewBox='0%200%20178%2025'%3E%3C/svg%3E" data-src="https://maribor24.si/wp-content/themes/maribor24-v2.1/img/logo-maribor24-4.svg" alt="" />`

I'm not well wersed enough in web technologies, but it looks like to me like the `src` is nonsensical, while `data-src` contains actual link to the image.

Is this something that needs to be supported or just ignored (#19)?

**Comment by bunglegrind** [comment]
No I think it's related to #10 . However, I still haven't touched the code related to SVG.

**Comment by bunglegrind** [comment]
btw, the image tag is fine. Some javascript library will perform the right transformation. 
I don't know where you got it, I suppose from the HTML source, but it's not where the extension extract the elements. If you're interested, you should look at the actual DOM, by pressing F12 or right clicking on the page and then selecting "analyze" (or inspect, if you're using chrome)

**Comment by bunglegrind** [comment]
I think it's fine now.There were multiple errors and bugs. I need to check better which characters are allowed  as filename, though.

**Comment by bunglegrind** [comment]
Please let me know if it's working or not.

**Comment by matejdro** [comment]
It seems to be working, thanks!
